spring:
  arthas: # 在线诊断组件
    enabled: false # 默认关闭，请按需开启
  h2: # 内存数据库
    console:
      enabled: true # 线上环境请勿设置
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource: # 数据源管理
#    username: sa
#    password: demo
#    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=TRUE
#    driver-class-name: org.h2.Driver
    username: root
    password: demo@123
    url: jdbc:mysql://localhost:3306/demo?rewriteBatchedStatements=true&useSSL=false&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    dynamic: # 多数据源，使用 @DS 切换
      enabled: false # 默认关闭，请按需开启
      strict: true
      primary: ds1
      datasource:
        ds1:
          username:
          password:
          url: jdbc:mysql://localhost:3306/ds1?rewriteBatchedStatements=true&useSSL=false&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
        ds2:
          username:
          password:
          url: jdbc:mysql://localhost:3306/ds2?rewriteBatchedStatements=true&useSSL=false&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
  shardingsphere: # 分库分表组件
    enabled: false # 默认关闭，请按需开启，目前 5.x 版本对 Liquibase 兼容性不友好
    datasource:
      names: ds1,ds2
      ds1:
        username: root
        password: demo@123
        url: jdbc:mysql://localhost:3306/ds1?rewriteBatchedStatements=true&useSSL=false&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
      ds2:
        username: root
        password: demo@123
        url: jdbc:mysql://localhost:3306/ds2?rewriteBatchedStatements=true&useSSL=false&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
    rules:
      replica-query:
        data-sources:
          rw:
            primary-data-source-name: ds1
            replica-data-source-names: ds2
            load-balancer-name: ROUND_ROBIN
            query-consistent: true
        load-balancers:
          round-robin:
            type: ROUND_ROBIN
            props:
              workId: 1
    props:
      sql.show: true
  liquibase:
    enabled: true # 默认开启，请按需关闭
  cloud:
    sentinel: # 服务流量治理
      enabled: false # 默认关闭，请按需开启
      transport:
        dashboard: localhost:8090
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            namespace: ${spring.cloud.nacos.config.namespace}
            groupId: sentinel
            dataId: ${spring.application.name}-flow-rule
            rule-type: flow
            data-type: json
  redis: # 缓存数据库
    enabled: false # 默认关闭，请按需开启
    password: demo@123
    timeout: 5000
    database: 1
    host: localhost
    port: 6379
  thymeleaf: # 模板引擎
    cache: false # 本地开发建议关闭缓存
  zipkin: # 链路跟踪
    base-url: http://localhost:9411
  kafka: # 消息队列
    bootstrap-servers: localhost:9092

rocketmq: # 消息队列
  enabled: false # 默认关闭，请按需开启
  name-server: localhost:9876;localhost:9876
  producer:
    group: ${spring.application.name}
    access-key:
    secret-key:
  consumer:
    group: ${spring.application.name}
    topic: demo

xxl: # 分布式调度平台
  job:
    enable: false # 默认关闭，请按需开启
    access-token:
    admin:
      addresses: http://localhost:8090/xxl-job
    executor:
      app-name: ${spring.application.name}
      ip:
      port:
      log-path: /logs/xxl-job/job-handler/
      log-retention-days: 7

cat: # 实时监控平台
  enabled: true # 默认关闭，请按需开启
  trace-mode: true # 开启访问观测
  home: /tmp
  servers: localhost
  tcp-port: 2280
  http-port: 8080

opentracing: # Jaeger 链路跟踪
  jaeger:
    enabled: false
    udp-sender:
      host: localhost
      port: 6831
